Validate that the generated required / enum validation is up to date

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -159,6 +159,13 @@ jobs:
             exit 1
           fi
 
+      - name: Verify that the generated enum and required fields are up to date
+        run: |
+          if ! ( make generate-validation && git diff --exit-code ); then
+            echo "The generated enum and required fields are not up to date. Please run 'make generate-validation' and commit the changes."
+            exit 1
+          fi
+
       # Github repo: https://github.com/ajv-validator/ajv-cli
       - name: Install ajv-cli
         run: npm install -g ajv-cli@5.0.0
